site_name: Creative Mobile Elements
nav:
    - Home: index.md
    - About: 
      - Contacts: manuals/about/about.md
      - Team: manuals/about/team.md
    - Documentation:
      - GettingStarted: manuals/getting_started.md
theme:
  name: material
  custom_dir: overrides
  logo: assets/press_logo_1.svg
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
  palette:
    primary: black
    accent: amber
markdown_extensions:
  - attr_list