site_name: Creative Mobile Elements
nav:
  - "User Guide":
    - "What is CME CloudPurchase?": index.md
    - "Getting Started": user_guide/getting_started.md
    - "Managing Cloud Environments": user_guide/managing_cloud_environments.md
    - "Usage Statistics & Monitoring": user_guide/usage_statistics.md
    - "Developer Guide":
      - "Making Validation Requests": user_guide/making_validation_requests.md
  - "API Reference":
    - api_reference/API.md
theme:
  name: material
  custom_dir: theme/
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow
  palette:
    primary: black
    accent: amber

markdown_extensions:
  - attr_list
  - lightgallery