site_name: CM Elements
copyright: Copyright &copy; 2010 – 2022 CREATIVE MOBILE OÜ

nav:
  - "User Guide":
    - "What is CME CloudPurchase?": index.md
    - "Getting Started": user_guide/getting_started.md
    - "Managing Cloud Environments": user_guide/managing_cloud_environments.md
    - "Usage Statistics & Monitoring": user_guide/usage_statistics.md
    - "Developer Guide":
      - "Making Validation Requests": user_guide/making_validation_requests.md
  - "API Reference":
    - api_reference/API.md
theme:
  name: material
  custom_dir: theme/
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow
  palette:
    primary: white
    accent: green
  logo: assets/CM_Elements_Logotype_full.svg
  favicon: assets/CM_Elements_Logotype.svg
  
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Creative_Mobile
      name: CME on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/CreativeMobile
      name: CME on Facebook 
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/creativemobile
      name: CME on Instagram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/creativemobile
      name: CME on Youtube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cmgames/
      name: CME on Linkedin


markdown_extensions:
  - attr_list
  - lightgallery
