site_name: Creative Mobile Elements
nav:
  - "User Guide":
    - "What is CME.CloudPurchase?": index.md
    - "Getting Started": user_guide/getting_started.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow
  palette:
    primary: black
    accent: amber

markdown_extensions:
  - attr_list
