site_name: ""
copyright: Copyright &copy; 2010 – 2022 CREATIVE MOBILE OÜ

repo_url: https://github.com/creative-mobile/CME.Documentation
edit_uri: edit/main/docs/
repo_name: CME.Documentation

nav:
  - "User Guide":
    - "What is CME CloudPurchase?": index.md
    - "Getting Started": user_guide/getting_started.md
    - "AWS Policy settings": user_guide/aws_policies.md
    - "Managing Cloud Environments": user_guide/managing_cloud_environments.md
    - "Usage Statistics & Monitoring": user_guide/usage_statistics.md
    - "Developer Guide":
      - "Making Validation Requests": user_guide/making_validation_requests.md
  - "API Reference":
    - "Namespaces":
      - api_reference/CME.CloudPurchase.md
theme:
  name: material
  custom_dir: theme/
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow
    - content.code.annotate
  palette:
    primary: white
    accent: light green
  logo: assets/CM_Elements_Logotype_full.svg
  favicon: assets/CM_Elements_Favicon.svg
  
extra:
  social:
    - icon: fontawesome/solid/house-chimney
      link: https://cme.dev
      name: CME
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CM_Elements
      name: CME on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/CMElements
      name: CME on Facebook 
    - icon: fontawesome/brands/discord
      link: https://discord.gg/vCRWDQJM
      name: CME on Discord
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCmVqOVnAbXFNFRKTvihcrgg
      name: CME on Youtube
    
    
extra_css:
  - stylesheets/style.css

markdown_extensions:
  - attr_list
  - lightgallery
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - md_in_html
